### ISSUE TITLE
gtk2 will not build on FreeDesktop 25.08

### ISSUE THREAD

**Issue by Eonfge** [flathub/shared-modules#408]
```
gtkitemfactory.c:1187:22: error: assignment to ‘GtkItemFactoryCallback’ {aka ‘void (*)(void)’} from incompatible pointer type ‘GtkMenuCallback’ {aka ‘void (*)(struct _GtkWidget *, void *)’} [-Wincompatible-pointer-types]
```

See here for an example:
https://github.com/flathub-infra/vorarbeiter/actions/runs/17395788182/job/49377448110

**Comment by Eonfge** [comment]
@TingPing As code-owner, you're the one having this cup trust upon you
