### ISSUE TITLE
gtk2-murrine-engine does not build with 24.08

### ISSUE THREAD

**Issue by Mailaender** [flathub/shared-modules#371]
```
./src/murrine_style.c: In function ‘murrine_set_widget_parameters’:
./src/murrine_style.c:133:30: error: implicit declaration of function ‘murrine_widget_is_ltr’; did you mean ‘murrine_widget_is_rgba’? [-Wimplicit-function-declaration]
  133 |         params->ltr        = murrine_widget_is_ltr ((GtkWidget*)widget);
      |                              ^~~~~~~~~~~~~~~~~~~~~
      |                              murrine_widget_is_rgba
./src/murrine_theme_main.c: In function ‘theme_init’:
./src/murrine_theme_main.c:31:9: error: implicit declaration of function ‘murrine_rc_style_register_types’; did you mean ‘murrine_rc_style_get_type’? [-Wimplicit-function-declaration]
   31 |         murrine_rc_style_register_types (module);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         murrine_rc_style_get_type
In file included from ./src/murrine_style.c:30:
./src/support.h:79:50: error: implicit declaration of function ‘murrine_object_is_a’; did you mean ‘murrine_widget_is_rgba’? [-Wimplicit-function-declaration]
   79 | #define MRN_IS_PROGRESS_BAR(object) ((object) && murrine_object_is_a ((GObject*)(object), "GtkProgressBar"))
      |                                                  ^~~~~~~~~~~~~~~~~~~
./src/murrine_style.c:174:42: note: in expansion of macro ‘MRN_IS_PROGRESS_BAR’
  174 |                 if (params->prelight && !MRN_IS_PROGRESS_BAR(widget)) //progressbar is prelight, no change in shade
      |                                          ^~~~~~~~~~~~~~~~~~~
./src/murrine_theme_main.c:32:9: error: implicit declaration of function ‘murrine_style_register_types’; did you mean ‘murrine_style_get_type’? [-Wimplicit-function-declaration]
   32 |         murrine_style_register_types (module);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         murrine_style_get_type
```
